---
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_formulae }}"

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_casks }}"

- name: Remove deprecated Homebrew formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: absent
  loop: "{{ homebrew_formulae_absent | default([]) }}"

- name: Remove deprecated Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: absent
  loop: "{{ homebrew_casks_absent | default([]) }}"
